#ifndef AHT20_CONFIG_H
#define AHT20_CONFIG_H

#define AHT20_IMPL_DEFAULT  0
#define AHT20_IMPL_FASTINT  1

#define AHT20_CONVERSION_MODE AHT20_IMPL_FASTINT

#define AHT20_TYPE_FLOAT 0
#define AHT20_TYPE_INT16 1

#if AHT20_CONVERSION_MODE == AHT20_IMPL_DEFAULT
    #define AHT20_CONVERSION_RETURN_TYPE AHT20_TYPE_FLOAT
#elif AHT20_CONVERSION_MODE == AHT20_IMPL_FASTINT
    #define AHT20_CONVERSION_RETURN_TYPE AHT20_TYPE_INT16
#else
    #error "Invalid AHT20_CONVERSION_MODE selected"
#endif

#endif // AHT20_CONFIG_H
